version: '3.8'

services:
  pomogo:
    container_name: pomogo
    build:
      context: ./../.
      dockerfile: build/package/Dockerfile
    volumes:
      - ./../.:/app
    restart: always
    ports:
      - "8513:8513"
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pomogo